// regions is based on the information here:
// https://www.azurespeed.com/Information/AzureRegions
package regions

import "github.com/grokify/mogo/location"

func RegionsAzure() location.Locations {
	return []location.Location{
		{
			RegionCode:                   "australiacentral",
			RegionName:                   "Australia Central-Canberra",
			RegionType:                   RegionTypeAzure,
			CityName:                     "Canberra",
			UNLOCODE:                     "AUCBR",
			ISO3166P1A2CountryCode:       "AU",
			ISO3166P2CountryCode:         "AU",
			ISO3166P2SubdivisionCodeFull: "AU-ACT",
			ISO3166P2SubdivisionCode:     "ACT",
			ISO3166P2SubdivisionName:     "Australian Capital Territory (ACT)",
			ISO3166P2SubdivisionCategory: location.SubdivisionTypeCapital,
			ReferenceURLs: []string{
				"https://www.datacenters.com/microsoft-azure-australia-central-canberra",
				"https://service.unece.org/trade/locode/au.htm",
				"https://www.abf.gov.au/help-and-support/ics/integrated-cargo-system-(ics)/software-developers/reference-materials/code-list/australian-un-locodes",
				"https://en.wikipedia.org/wiki/ISO_3166-2:AU",
			},
			SubregionsCount: 1,
		},
		{
			RegionCode:                   "australiaeast",
			RegionName:                   "Australia East-New South Wales",
			RegionType:                   RegionTypeAzure,
			CityName:                     "Sydney",
			UNLOCODE:                     "AUSYD",
			ISO3166P2SubdivisionCodeFull: "AU-NSW",
			ISO3166P1A2CountryCode:       "AU",
			ISO3166P2CountryCode:         "AU",
			ISO3166P2SubdivisionCode:     "NSW",
			ISO3166P2SubdivisionName:     "New South Wales",
			ISO3166P2SubdivisionCategory: location.SubdivisionTypeState,
			ReferenceURLs: []string{
				"https://www.datacenters.com/microsoft-azure-australia-east-new-south-wales",
				"https://service.unece.org/trade/locode/au.htm",
				"https://www.abf.gov.au/help-and-support/ics/integrated-cargo-system-(ics)/software-developers/reference-materials/code-list/australian-un-locodes",
				"https://en.wikipedia.org/wiki/ISO_3166-2:AU",
			},
			SubregionsCount: 3,
		},
		{
			RegionCode:                   "australiasoutheast",
			RegionName:                   "Australia Southeast-Victoria",
			RegionType:                   RegionTypeAzure,
			CityName:                     "Melbourne",
			UNLOCODE:                     "AUMEL",
			ISO3166P2SubdivisionCodeFull: "AU-VIC",
			ISO3166P1A2CountryCode:       "AU",
			ISO3166P2CountryCode:         "AU",
			ISO3166P2SubdivisionCode:     "VIC",
			ISO3166P2SubdivisionName:     "Victoria",
			ISO3166P2SubdivisionCategory: location.SubdivisionTypeState,
			ReferenceURLs: []string{
				"https://www.datacenters.com/microsoft-azure-australia-southeast-victoria",
				"https://service.unece.org/trade/locode/au.htm",
				"https://www.abf.gov.au/help-and-support/ics/integrated-cargo-system-(ics)/software-developers/reference-materials/code-list/australian-un-locodes",
				"https://en.wikipedia.org/wiki/ISO_3166-2:AU",
			},
			SubregionsCount: 1,
		},
		{
			RegionCode:                   "canadacentral",
			RegionName:                   "Canada Central-Toronto",
			RegionType:                   RegionTypeAzure,
			UNLOCODE:                     "CATOR",
			CityName:                     "Toronto",
			ISO3166P1A2CountryCode:       "CA",
			ISO3166P2SubdivisionCodeFull: "CA-ON",
			ISO3166P2CountryCode:         "CA",
			ISO3166P2SubdivisionCode:     "ON",
			ISO3166P2SubdivisionName:     "Ontario",
			ISO3166P2SubdivisionCategory: location.SubdivisionTypeProvince,
			ReferenceURLs: []string{
				"https://www.datacenters.com/microsoft-azure-canada-central-toronto",
				"https://service.unece.org/trade/locode/ca.htm",
				"https://en.wikipedia.org/wiki/ISO_3166-2:CA",
			},
			SubregionsCount: 3,
		},
		{
			RegionCode:                   "canadaeast",
			RegionName:                   "Canada East-Quebec City",
			RegionType:                   RegionTypeAzure,
			UNLOCODE:                     "CAQUE",
			CityName:                     "Quebec",
			ISO3166P1A2CountryCode:       "CA",
			ISO3166P2SubdivisionCodeFull: "CA-QC",
			ISO3166P2CountryCode:         "CA",
			ISO3166P2SubdivisionCode:     "QC",
			ISO3166P2SubdivisionName:     "Quebec",
			ISO3166P2SubdivisionCategory: location.SubdivisionTypeProvince,
			ReferenceURLs: []string{
				"https://www.datacenters.com/microsoft-azure-canada-east-quebec-city",
				"https://service.unece.org/trade/locode/ca.htm",
				"https://en.wikipedia.org/wiki/ISO_3166-2:CA",
			},
			SubregionsCount: 1,
		},
		{
			RegionCode:                   "centralus",
			RegionName:                   "Des Moines Data Center",
			RegionType:                   RegionTypeAzure,
			UNLOCODE:                     "USWEM",
			CityName:                     "West Des Moines",
			ISO3166P1A2CountryCode:       "US",
			ISO3166P2SubdivisionCodeFull: "US-IA",
			ISO3166P2CountryCode:         "US",
			ISO3166P2SubdivisionCode:     "IA",
			ISO3166P2SubdivisionName:     "Iowa",
			ISO3166P2SubdivisionCategory: location.SubdivisionTypeState,
			ReferenceURLs: []string{
				"https://www.datacenters.com/microsoft-azure-des-moines",
				"https://service.unece.org/trade/locode/us.htm",
				"https://en.wikipedia.org/wiki/ISO_3166-2:US",
			},
			SubregionsCount: 3,
		},
		{
			RegionCode:                   "eastus",
			RegionName:                   "East US-Virginia",
			RegionType:                   RegionTypeAzure,
			UNLOCODE:                     "USZYD",
			CityName:                     "Boydton",
			ISO3166P1A2CountryCode:       "US",
			ISO3166P2SubdivisionCodeFull: "US-VA",
			ISO3166P2CountryCode:         "US",
			ISO3166P2SubdivisionCode:     "VA",
			ISO3166P2SubdivisionName:     "Virginia",
			ISO3166P2SubdivisionCategory: location.SubdivisionTypeState,
			ReferenceURLs: []string{
				"https://www.datacenters.com/microsoft-azure-east-us-virginia",
				"https://service.unece.org/trade/locode/us.htm",
				"https://en.wikipedia.org/wiki/ISO_3166-2:US",
			},
			SubregionsCount: 3,
		},
		{
			RegionCode:                   "eastus2",
			RegionName:                   "East US 2 - Virginia",
			RegionType:                   RegionTypeAzure,
			UNLOCODE:                     "USZYD",
			CityName:                     "Boydton",
			ISO3166P1A2CountryCode:       "US",
			ISO3166P2SubdivisionCodeFull: "US-VA",
			ISO3166P2CountryCode:         "US",
			ISO3166P2SubdivisionCode:     "VA",
			ISO3166P2SubdivisionName:     "Virginia",
			ISO3166P2SubdivisionCategory: location.SubdivisionTypeState,
			ReferenceURLs: []string{
				"https://www.datacenters.com/microsoft-azure-east-us-2-virginia",
				"https://service.unece.org/trade/locode/us.htm",
				"https://en.wikipedia.org/wiki/ISO_3166-2:US",
			},
			SubregionsCount: 3,
		},
		{
			RegionCode:                   "northcentralus",
			RegionName:                   "North Central US-Illinois",
			RegionType:                   RegionTypeAzure,
			UNLOCODE:                     "USNTI",
			CityName:                     "Northlake",
			ISO3166P1A2CountryCode:       "US",
			ISO3166P2SubdivisionCodeFull: "US-IL",
			ISO3166P2CountryCode:         "US",
			ISO3166P2SubdivisionCode:     "IL",
			ISO3166P2SubdivisionName:     "Illinois",
			ISO3166P2SubdivisionCategory: location.SubdivisionTypeState,
			ReferenceURLs: []string{
				"https://www.datacenters.com/microsoft-azure-north-central-us-illinois",
				"https://service.unece.org/trade/locode/us.htm",
				"https://en.wikipedia.org/wiki/ISO_3166-2:US",
			},
			SubregionsCount: 1,
		},
		{
			RegionCode:                   "northeurope",
			RegionName:                   "North Europe-Ireland",
			RegionType:                   RegionTypeAzure,
			UNLOCODE:                     "IEDUB",
			CityName:                     "Dublin",
			ISO3166P1A2CountryCode:       "IE",
			ISO3166P2SubdivisionCodeFull: "IE-D",
			ISO3166P2CountryCode:         "IE",
			ISO3166P2SubdivisionCode:     "D",
			ISO3166P2SubdivisionName:     "County Dublin",
			ISO3166P2SubdivisionCategory: location.SubdivisionTypeCounty,

			ReferenceURLs: []string{
				"https://www.datacenters.com/microsoft-azure-north-europe-ireland",
			},
			SubregionsCount: 3,
		},
		{
			RegionCode:                   "norwayeast",
			RegionName:                   "Norway East-Oslo",
			RegionType:                   RegionTypeAzure,
			UNLOCODE:                     "NOOSL",
			CityName:                     "Oslo",
			ISO3166P1A2CountryCode:       "NO",
			ISO3166P2SubdivisionCodeFull: "NO-03",
			ISO3166P2CountryCode:         "NO",
			ISO3166P2SubdivisionCode:     "03",
			ISO3166P2SubdivisionName:     "Oslo",
			ISO3166P2SubdivisionCategory: location.SubdivisionTypeCounty,
			ReferenceURLs: []string{
				"https://www.datacenters.com/microsoft-azure-norway-east-oslo",
				"https://service.unece.org/trade/locode/no.htm",
			},
			SubregionsCount: 3,
		},
		{
			RegionCode:                   "southcentralus",
			RegionName:                   "South Central US-Texas",
			RegionType:                   RegionTypeAzure,
			UNLOCODE:                     "USTSA",
			CityName:                     "San Antonio",
			ISO3166P1A2CountryCode:       "US",
			ISO3166P2SubdivisionCodeFull: "US-TX",
			ISO3166P2CountryCode:         "US",
			ISO3166P2SubdivisionCode:     "TX",
			ISO3166P2SubdivisionName:     "Texas",
			ISO3166P2SubdivisionCategory: location.SubdivisionTypeState,
			ReferenceURLs: []string{
				"https://www.datacenters.com/microsoft-azure-south-central-us-texas",
			},
			SubregionsCount: 3,
		},
		{
			RegionCode:                   "southeastasia",
			RegionName:                   "Southeast Asia-Singapore",
			RegionType:                   RegionTypeAzure,
			CityName:                     "Singapore",
			UNLOCODE:                     "SGSIN",
			ISO3166P1A2CountryCode:       "SG",
			ISO3166P2SubdivisionCodeFull: "SG",
			ISO3166P2CountryCode:         "SG",
			ISO3166P2SubdivisionCode:     "",
			ISO3166P2SubdivisionName:     "",
			ISO3166P2SubdivisionCategory: "",
			ReferenceURLs: []string{
				"https://www.datacenters.com/microsoft-azure-southeast-asia-singapore",
			},
			SubregionsCount: 3,
		},
		{
			RegionCode:                   "switzerlandnorth",
			RegionName:                   "Switzerland North-Zurich",
			RegionType:                   RegionTypeAzure,
			CityName:                     "Zurich",
			UNLOCODE:                     "CHZRH",
			ISO3166P1A2CountryCode:       "CH",
			ISO3166P2SubdivisionCodeFull: "CH-ZH",
			ISO3166P2CountryCode:         "CH",
			ISO3166P2SubdivisionCode:     "ZH",
			ISO3166P2SubdivisionName:     "Canton of Zurich",
			ISO3166P2SubdivisionCategory: location.SubdivisionTypeCanton,
			ReferenceURLs: []string{
				"https://www.datacenters.com/microsoft-azure-switzerland-north-zurich",
			},
			SubregionsCount: 3,
		},
		{
			RegionCode:                   "uksouth",
			RegionName:                   "UK South-London",
			RegionType:                   RegionTypeAzure,
			CityName:                     "London",
			ISO3166P1A2CountryCode:       "GB",
			UNLOCODE:                     "GBLON",
			ISO3166P2SubdivisionCodeFull: "GB-ENG",
			ISO3166P2CountryCode:         "GB",
			ISO3166P2SubdivisionCode:     "ENG",
			ISO3166P2SubdivisionName:     "England",
			ISO3166P2SubdivisionCategory: location.SubdivisonTypeCountry,
			ReferenceURLs: []string{
				"https://www.datacenters.com/microsoft-azure-uk-south-london",
			},
			SubregionsCount: 3,
		},
		{
			RegionCode:                   "westeurope",
			RegionName:                   "West Europe-Netherlands",
			RegionType:                   RegionTypeAzure,
			CityName:                     "Schiphol",
			UNLOCODE:                     "NLSPL",
			ISO3166P1A2CountryCode:       "NL",
			ISO3166P2SubdivisionCodeFull: "NL-NH",
			ISO3166P2CountryCode:         "NL",
			ISO3166P2SubdivisionCode:     "NH",
			ISO3166P2SubdivisionName:     "North Holland",
			ISO3166P2SubdivisionCategory: location.SubdivisionTypeProvince,
			ReferenceURLs: []string{
				"https://www.datacenters.com/microsoft-azure-west-europe-netherlands",
			},
			SubregionsCount: 3,
		},
		{
			RegionCode:                   "westus",
			RegionName:                   "West US-California",
			RegionType:                   RegionTypeAzure,
			CityName:                     "Fresno",
			UNLOCODE:                     "USFAT",
			ISO3166P1A2CountryCode:       "US",
			ISO3166P2SubdivisionCodeFull: "US-CA",
			ISO3166P2CountryCode:         "US",
			ISO3166P2SubdivisionCode:     "CA",
			ISO3166P2SubdivisionName:     "California",
			ISO3166P2SubdivisionCategory: location.SubdivisionTypeState,
			ReferenceURLs: []string{
				"https://www.datacenters.com/microsoft-azure-west-us-california",
			},
			SubregionsCount: 1,
		},
		{
			RegionCode:                   "westus2",
			RegionName:                   "West US 2-Washington",
			RegionType:                   RegionTypeAzure,
			CityName:                     "Quincy",
			UNLOCODE:                     "USQNC",
			ISO3166P1A2CountryCode:       "US",
			ISO3166P2SubdivisionCodeFull: "US-WA",
			ISO3166P2CountryCode:         "US",
			ISO3166P2SubdivisionCode:     "WA",
			ISO3166P2SubdivisionName:     "Washington",
			ISO3166P2SubdivisionCategory: location.SubdivisionTypeState,
			ReferenceURLs: []string{
				"https://www.datacenters.com/microsoft-azure-west-us-2-washington",
			},
			SubregionsCount: 3,
		},
	}
}
